# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jzx/StudyCpp/ConnPool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jzx/StudyCpp/ConnPool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jzx/StudyCpp/ConnPool/CMakeFiles /home/jzx/StudyCpp/ConnPool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jzx/StudyCpp/ConnPool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mysqltest

# Build rule for target.
mysqltest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysqltest
.PHONY : mysqltest

# fast build rule for target.
mysqltest/fast:
	$(MAKE) -f CMakeFiles/mysqltest.dir/build.make CMakeFiles/mysqltest.dir/build
.PHONY : mysqltest/fast

#=============================================================================
# Target rules for targets named redispool_test

# Build rule for target.
redispool_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 redispool_test
.PHONY : redispool_test

# fast build rule for target.
redispool_test/fast:
	$(MAKE) -f CMakeFiles/redispool_test.dir/build.make CMakeFiles/redispool_test.dir/build
.PHONY : redispool_test/fast

#=============================================================================
# Target rules for targets named redishelper_test

# Build rule for target.
redishelper_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 redishelper_test
.PHONY : redishelper_test

# fast build rule for target.
redishelper_test/fast:
	$(MAKE) -f CMakeFiles/redishelper_test.dir/build.make CMakeFiles/redishelper_test.dir/build
.PHONY : redishelper_test/fast

tests/mysqltest.o: tests/mysqltest.cpp.o

.PHONY : tests/mysqltest.o

# target to build an object file
tests/mysqltest.cpp.o:
	$(MAKE) -f CMakeFiles/mysqltest.dir/build.make CMakeFiles/mysqltest.dir/tests/mysqltest.cpp.o
.PHONY : tests/mysqltest.cpp.o

tests/mysqltest.i: tests/mysqltest.cpp.i

.PHONY : tests/mysqltest.i

# target to preprocess a source file
tests/mysqltest.cpp.i:
	$(MAKE) -f CMakeFiles/mysqltest.dir/build.make CMakeFiles/mysqltest.dir/tests/mysqltest.cpp.i
.PHONY : tests/mysqltest.cpp.i

tests/mysqltest.s: tests/mysqltest.cpp.s

.PHONY : tests/mysqltest.s

# target to generate assembly for a file
tests/mysqltest.cpp.s:
	$(MAKE) -f CMakeFiles/mysqltest.dir/build.make CMakeFiles/mysqltest.dir/tests/mysqltest.cpp.s
.PHONY : tests/mysqltest.cpp.s

tests/redishelper_test.o: tests/redishelper_test.cpp.o

.PHONY : tests/redishelper_test.o

# target to build an object file
tests/redishelper_test.cpp.o:
	$(MAKE) -f CMakeFiles/redishelper_test.dir/build.make CMakeFiles/redishelper_test.dir/tests/redishelper_test.cpp.o
.PHONY : tests/redishelper_test.cpp.o

tests/redishelper_test.i: tests/redishelper_test.cpp.i

.PHONY : tests/redishelper_test.i

# target to preprocess a source file
tests/redishelper_test.cpp.i:
	$(MAKE) -f CMakeFiles/redishelper_test.dir/build.make CMakeFiles/redishelper_test.dir/tests/redishelper_test.cpp.i
.PHONY : tests/redishelper_test.cpp.i

tests/redishelper_test.s: tests/redishelper_test.cpp.s

.PHONY : tests/redishelper_test.s

# target to generate assembly for a file
tests/redishelper_test.cpp.s:
	$(MAKE) -f CMakeFiles/redishelper_test.dir/build.make CMakeFiles/redishelper_test.dir/tests/redishelper_test.cpp.s
.PHONY : tests/redishelper_test.cpp.s

tests/redispool_test.o: tests/redispool_test.cpp.o

.PHONY : tests/redispool_test.o

# target to build an object file
tests/redispool_test.cpp.o:
	$(MAKE) -f CMakeFiles/redispool_test.dir/build.make CMakeFiles/redispool_test.dir/tests/redispool_test.cpp.o
.PHONY : tests/redispool_test.cpp.o

tests/redispool_test.i: tests/redispool_test.cpp.i

.PHONY : tests/redispool_test.i

# target to preprocess a source file
tests/redispool_test.cpp.i:
	$(MAKE) -f CMakeFiles/redispool_test.dir/build.make CMakeFiles/redispool_test.dir/tests/redispool_test.cpp.i
.PHONY : tests/redispool_test.cpp.i

tests/redispool_test.s: tests/redispool_test.cpp.s

.PHONY : tests/redispool_test.s

# target to generate assembly for a file
tests/redispool_test.cpp.s:
	$(MAKE) -f CMakeFiles/redispool_test.dir/build.make CMakeFiles/redispool_test.dir/tests/redispool_test.cpp.s
.PHONY : tests/redispool_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mysqltest"
	@echo "... rebuild_cache"
	@echo "... redispool_test"
	@echo "... redishelper_test"
	@echo "... tests/mysqltest.o"
	@echo "... tests/mysqltest.i"
	@echo "... tests/mysqltest.s"
	@echo "... tests/redishelper_test.o"
	@echo "... tests/redishelper_test.i"
	@echo "... tests/redishelper_test.s"
	@echo "... tests/redispool_test.o"
	@echo "... tests/redispool_test.i"
	@echo "... tests/redispool_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

